### PR TITLE
WIP: refactoring

### PR DESCRIPTION
**Pull request by lc-d**
- Remove site specific content 
- Remove hardcoded html
- Change main font
- Remove old classes form template
- Fix homepage featured menu
- Fix download extension template
- Fix color variation for subsites 
- Fix header and footer menu

### CODE REVIEW

**Comment by privatemaker** [comment]
I not sure why you are doing some of this re-factoring. These things make
sense as they are oversights on my part:

`.Hugo` -> `hugo`
`clear` -> `clearfix`

Moving the <script src="..."> tags to the footer breaks the order of JS
being loaded on pages now.

You deleted my custom CSS classes in `assets/_components` for Facebook
Reality Check.

Why are you deleting all the slides like?

layouts/partials/slides/livedemo.md
layouts/partials/slides/*

As I understand it, Hugo needs these to be in the theme.

**Comment by lc-d** [comment]
The idea is simple, this theme must be general, this is not the facebook subsite, so I remove all part that belong to sub site.
I need to start fresh for youtube, If you like, do not merge and keep working as you want.

**Comment by privatemaker** [comment]
As I outlined in the README, the idea is to add sub-site things to this repo

https://github.com/tracking-exposed/hugo-theme-trex#sass-architecture

> The idea is simple, this theme must be general

My thinking is to keep *all* the SASS / CSS in this repo and also some
globally shared JS logic such as API wrappers, libraries, etc...

Site specific JS logic (reality-check.js, zuckless-news.js) will stay in the
sub-site repos as it doesn't make any sense for them to be here.

> this is not the facebook subsite so I remove all part that belong to sub site.

Your approach splinters CSS classes / components and makes hard to get an
overview of what exists globally as well as re-use. There is also the issue of:

1. Requiring extra SASS compiling step for `facebook.scss` in sub-site

Or

2. Only load CSS so you get no access to SASS variables

> I need to start fresh for youtube

If you want to make it more explicit, change _components.scss to _facebook.scss 
but please keep it in this repo. So you could do _youtube.scss also...

> If you like, do not merge and keep working as you want.

A bunch of your little changes were great, but please don't go chopping
out an re-organizing the overall architecture and loading order of JS.

**Comment by vecna** [comment]
Hi all, I'm talking with the both of you to figure out the best solution.

The underlay necessity behind this PR was to keep this repo "more generic as possible" but also, we have realized yesterday, some site-specific layout should be inside the 'themes/trex' directory. this is why we have to force these files ( https://github.com/tracking-exposed/youtube.tracking.exposed/tree/master/themes/trex/layouts/yttrex ) despite in the site-specific repository we have `.gitignore` preventing file from `themes/trex`. This made me clear, we might have made a mistake in keeping a shared theme because the site-specific customization should be put here anyway: this might imply, this repository can't be generic at all, and we might not even benefit in keeping it as a shared skeleton. 

An additional issue were the slides (I though they should be in the https://github.com/tracking-exposed/tracking.exposed as content, and the layout something like `generic-slideshow.html` in this shared theme).

The final mistake of this PR is that it contains **more than one reasons** to be done. Some of them can be OK [@privatemaker you mention some changes are great, can you say which?], others changes should be debated and agree in order to avoid to break the other developers code (which for me is the only things that matter. I prefer code redundancy [for example, every site specific has a theme copied] and misalignment [for example, button version 2 present only in half sites] rather than breaking other people work by surprise). 

A good theory in project with more than three people, is that github issue describe what we are doing, and every commit reference them, so we can easily understand why changes have been done.

**Comment by privatemaker** [comment]
> https://github.com/tracking-exposed/youtube.tracking.exposed/tree/master/themes/trex/layouts/yttrex
> ) despite in the site-specific repository we have `.gitignore` preventing
> file from `themes/trex`.

This is the extact opposite approach to how I had thought about this. The
"app" layout is what I created to be as empty of a template as possible.

https://github.com/tracking-exposed/hugo-theme-trex/tree/master/layouts/app

See how the Reality Check app is using this layout

https://github.com/tracking-exposed/facebook.tracking.exposed/blob/master/content/reality-check.html

This makes a shared template that includes navbar + footer for all sites with
the maximum flexibility to customize that "app" which I think is a nice UX.

> This made me clear, we might have made a mistake
> in keeping a shared theme because the site-specific customization should
> be put here anyway: this might imply, this repository can't be generic at
> all, and we might not even benefit in keeping it as a shared skeleton.

Yes. This repo was never meant to be generic or a starter skeleton, but
rather a "theme" for ALL the TrEx sites, basically a git submodule eve if
you no use submodules technically.

> An additional issue were the slides (I though they should be in the
> https://github.com/tracking-exposed/tracking.exposed as content, and the
> layout something like `generic-slideshow.html` in this shared theme).

Moving the slides to tracking.exposed totally makes since. I was having a
hard time figuring out how to include partials from theme + parent site as
you can't do "include" from within a content file.

> The final mistake of this PR is that it contains **more than one reasons**
> to be done. Some of them can be OK [@privatemaker you mention some changes
> are great, can you say which?],

- `.Hugo` -> `hugo`
- `clear` -> `clearfix`
- `<nav>` -> `<header>`
- Other CSS optimizations seem fine

> I prefer code redundancy [for example, every site specific has a theme copied]
> and misalignment [for example, button version 2 present only in half sites]
> rather than breaking other people work by surprise).

Yes, out of date version is better than broken code 1000% agree.
If we agree to only push to dev branch until review + tested on all sites we
could automate updates with cron to make it less work...

> A good theory in project with more than three people, is that github issue
> describe what we are doing, and every commit reference them, so we can
> easily understand why changes have been done.

Yes!! Since we are not colleagues who talk everyday or share office, we
should undertake re-factors and big things *only* with much communication
before doing it. Ideally @tag people when input is needed.

**Comment by vecna** [comment]
Thanks for the input from both of you, some actionable progress in regards of this branch:

1. the `app` design is clear now, and so it is the separation between what is in `hugo-theme-trex` and the domain specific repo. @privatemaker a follow-up question: does it means we should have a here in `layouts` a `slideshow.html` and then in the domain specific repos, the slides content using `type: slide`?
2. Considering this repository is containing some generalized files, the css/js should have generic names. If something contains material used by reality-check, should at least be named 'facebook' or under a folder that make it clear 
3. @lc-d will take care in restore and revert some changes, such as the javascript loading sequence. he'll keep updating this branch and compatibility with current realitycheck development should be verified before merging.
4. the partial should be the high level components of the UX, they should be generic.

Do I understood correctly? give your github-reaction of approval or comment :) thanks

**Comment by lc-d** [comment]
On monday I’ll try to refactoring in the right way the theme and to fix YouTube sub site accordingly.

**Comment by lc-d** [comment]
Hi @privatemaker, check out the last commits and let me know if it sound good to you.

**Comment by vecna** [comment]
Thanks @lc-d and @privatemaker, merged

**Pull request merged**
